name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t simple-web-detector:ci .

      - name: Start services
        run: |
          docker run -d --rm -p 8080:8080 -p 9090:9090 --name app simple-web-detector:ci

      - name: Wait for health
        run: |
          for i in {1..120}; do
            if curl -fsS http://localhost:8080/healthz >/dev/null; then
              echo "Service is healthy"; exit 0; fi; sleep 5; done; exit 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run tests
        env:
          DOCKER_IP: localhost
        run: pytest -q tests.py

      - name: Logs on failure
        if: failure()
        run: |
          docker logs app || true
          curl -s http://localhost:8080/metrics || true

      - name: Stop services
        if: always()
        run: docker rm -f app || true


